# Generated by Django 3.0.5 on 2020-10-12 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0002_auto_20201012_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='img',
            new_name='img_pic',
        ),
    ]
